DROP DATABASE IF EXISTS BANK_APPLICATION;
CREATE DATABASE BANK_APPLICATION;
USE BANK_APPLICATION;

-- database tables

DROP TABLE IF EXISTS CLIENTS;
CREATE TABLE CLENTS(
    Client_ID INT PRIMARY KEY AUTO_INCREMENT,
    Client_firstName VARCHAR(50) NOT NULL,
    Client_lastName VARCHAR(50) NOT NULL,
    Client_address VARCHAR(100) NOT NULL,
    Client_phoneNumber VARCHAR(50) NOT NULL,
    Client_address VARCHAR(50) NOT NULL,
    Client_userName VARCHAR(50) NOT NULL,
    Client_password VARCHAR(50) NOT NULL,

)
DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES(
    Employee_ID INT PRIMARY KEY,
    Employee_userName VARCHAR(50) NOT NULL,
    Employee_passowrd VARCHAR(50) NOT NULL

)

DROP TABLE IF EXISTS DEBITCARDS;
CREATE TABLE DEBITCARDS(
    Employee_ID INT PRIMARY KEY,
    Employee_userName VARCHAR(50) NOT NULL,
    Employee_passowrd VARCHAR(50) NOT NULL

)

